global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'microservices-monitor'

scrape_configs:
  # Microservices
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        regex: '(.+):.*'
        replacement: '${1}'

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        regex: '(.+):.*'
        replacement: '${1}'

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-service:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        regex: '(.+):.*'
        replacement: '${1}'

  - job_name: 'map-service'
    metrics_path: '/metrics'  
    static_configs:
      - targets: ['map-service:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        regex: '(.+):.*'
        replacement: '${1}'

  - job_name: 'ai-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai-service:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        regex: '(.+):.*'
        replacement: '${1}'

  - job_name: 'report-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['report-service:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        regex: '(.+):.*'
        replacement: '${1}'

  # Database exporters
  - job_name: 'postgres-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mongodb-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Redis exporter
  - job_name: 'redis-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis-exporter:9121']
