name: CI - Microservices Auth

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services
      run: docker-compose up --build -d
      working-directory: ./microservices-auth

    # You can add steps here to run tests if your services have them.
    # Example (assuming tests can be run with docker-compose exec):
    # - name: Run Auth Service tests
    #   run: docker-compose exec auth-service pytest /app/tests
    #   working-directory: ./microservices-auth

    - name: Check running containers
      run: docker-compose ps
      working-directory: ./microservices-auth

    - name: Stop services
      run: docker-compose down
      working-directory: ./microservices-auth 