name: CI

on: [push, pull_request]

jobs:
  test-auth-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: auth_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd auth-service
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd auth-service
          pytest

  test-user-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd user-service
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd user-service
          pytest

  test-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd api-gateway
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd api-gateway
          pytest 